require("babel-runtime/regenerator")
require("react-hot-loader/patch")
require("babel-register")
require("webpack-hot-middleware/client?reload=true")
require("./main.sass")
require("./index.html")
require("./app.js")